name: using github actors
on: 
  push:
jobs:
  github-actor:
    runs-on: ubuntu-latest
    env: 
      Actor: ${{ github.actor}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: echoing actor
        run: |
          echo $Actor
          pwd
          ls
          python sqaure.py
      
