name: using github actors
on: 
  push:
  workflow_dispatch:
jobs:
  github-actor:
    runs-on: ubuntu-latest
    env: 
      Actor: ${{ github.actor}}
      MEDISTRANO_PROJECT_NAME: "Siteinvoices"
      MEDISTRANO_STAGE_NAME: "Distro"
      MEDISTRANO_TOKEN: ${{ secrets.MEDISTRANO_TOKEN }}
      EKS_SWITCH: "off"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: echoing actor
        run: |
          echo $Actor
          pwd
          ls
      - name: running python script
        run: |
          python3 square.py
      - name: searching images
        run: |
          pwd
          ls 
          cd docs/
          ls
      - name: checking installations
        run: |
          python3 installation.py
      - name: running ir.py
        run: |
          python3 IR.py
