name: using outputs and needs
on: 
  workflow_dispatch:
    inputs:
      a1: 
        description: provide 1st integer
        required: true
        type: number
      a2:
        description: provide 2nd string
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: step1
        id: step1
        # run: |
        #   x1= ${{ inputs.a1 }}
        #   string1= ${{ inputs.a2 }}
        run: |
          echo "::set-output name=test::hello"
          
      - name: step2
        # run: |
        #   echo "step 2 outputs ${{ steps.step1.outputs.x1}}"
        #   echo "step 2 outputs ${{ steps.step1.outputs.string1}}"
        run: |
          echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: |
          echo ${{ jobs.job1.outputs.output1 }} ${{ jobs.job1.outputs.output2}}
