name: using outputs and needs
on: 
  workflow_dispatch:
    inputs:
      a1: 
        description: provide 1st integer
        required: true
        type: number
      a2:
        description: provide 2nd string
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test2 }}
      output3: ${{ steps.step3.outputs.test3 }}
    steps:
      - name: step1
        id: step1
        run: |
          echo "::set-output name=test::hello"
          
      - name: step2
        run: |
          echo "::set-output name=test2::world"
      
      - name: step3
        run: |
          x1=${{ fromJSON(github.event.inputs.a1) }}
          echo "::set-output name=test3::$x1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: |
          echo ${{ needs.job1.outputs.output1 }}
          echo ${{ needs.job1.outputs.output2 }}
          echo ${{ needs.job1.outputs.output3 }}
