name: workflow2
on:
  workflow_dispatch:
    inputs:
      A1:
        description: 1stinteger
        required: true
        type: number
      B1:
        description: 2ndiinteger
        required: true
        type: number
jobs:
  call_sum_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print pwd
        run: |
          echo pwd
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: uses sum workflow
        uses: sidgupta-mdsol/github-actions/.github/workflows/sum.yml@main
        with: |
          A: ${{ inputs.A1 }}
          B: ${{ inputs.B1 }}
      
