name: workflow2
on:
  workflow_dispatch:
     inputs:
      A1:
        description: 1stinteger
        required: true
        type: number
      B1:
        description: 2ndiinteger
        required: true
        type: number
jobs:
  call_sum_workflow:
    uses: sidgupta-mdsol/github-actions/.github/workflows/sum.yml@main
    with: |
      A: ${{ github.events.inputs.A1 }}
      B: ${{ github.events.inputs.B1 }}
  
