name: workflow2
on:
  workflow_dispatch:
    inputs:
      A1:
        description: 1st integer
        required: true
        type: number
        
        
      B1:
        description: 2nd integer
        required: true
        type: number
jobs:
  call_sum_workflow:
    
    uses: sidgupta-mdsol/github-actions/.github/workflows/sum.yml@main
    with:
      A:  ${{ 'github.event.inputs.A1' }}
      B:  ${{ 'github.event.inputs.B1' }}
